-- Run this in Supabase SQL Editor

-- 1. Create Customers Table
CREATE TABLE IF NOT EXISTS customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  phone text,
  email text,
  address text,
  credit_limit numeric(12,2) DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 2. Update Sales Table
ALTER TABLE sales ADD COLUMN IF NOT EXISTS customer_id bigint REFERENCES customers(id);
ALTER TABLE sales ADD COLUMN IF NOT EXISTS invoice_number text UNIQUE;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS status text CHECK (status IN ('paid', 'pending', 'overdue')) DEFAULT 'paid';
ALTER TABLE sales ADD COLUMN IF NOT EXISTS due_date date;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS amount_paid numeric(12,2) DEFAULT 0;

-- 3. Create Payments Table
CREATE TABLE IF NOT EXISTS payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id bigint REFERENCES sales(id) ON DELETE CASCADE,
  amount numeric(12,2) NOT NULL,
  payment_date date NOT NULL DEFAULT current_date,
  payment_method text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 4. Indexes
CREATE INDEX IF NOT EXISTS idx_sales_customer ON sales(customer_id);
CREATE INDEX IF NOT EXISTS idx_sales_status ON sales(status);
CREATE INDEX IF NOT EXISTS idx_payments_sale ON payments(sale_id);
